# AnyonicHO Network Status Check
# Autogenerated by Gemini CLI to harmonize the network

$status = @{
    Timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    Agents = @{
        Gemini = @{ Status = "Active"; Config = "$env:USERPROFILE\.gemini\GEMINI.md" }
        Claude = @{ Status = "Pending"; Config = "$env:USERPROFILE\.claude\CLAUDE.md" }
    }
    Components = @{}
    Issues = @()
}

Write-Host "--- AnyonicHO Network Status Check ---" -ForegroundColor Cyan

# 1. Check Coherence MCP
$mcpPath = "$env:USERPROFILE\coherence-mcp"
if (Test-Path $mcpPath) {
    $status.Components["CoherenceMCP"] = "Installed (Local)"
    Write-Host "  [OK] Coherence MCP found at $mcpPath" -ForegroundColor Green
} else {
    $status.Components["CoherenceMCP"] = "Missing"
    $status.Issues += "Coherence MCP repository not found in user root"
    Write-Host "  [WARN] Coherence MCP repository not found" -ForegroundColor Yellow
}

# 2. Check Critical Context Files
$criticalFiles = @{
    "$env:USERPROFILE\.gemini\GEMINI.md" = "Gemini Context"
    "$env:USERPROFILE\.claude\CLAUDE.md" = "Claude Context"
    "$env:USERPROFILE\AnyonicHO\WAVE_GITHUB_ANALYSIS.md" = "WAVE Analysis"
}

foreach ($file in $criticalFiles.Keys) {
    if (Test-Path $file) {
        Write-Host "  [OK] Found $($criticalFiles[$file])" -ForegroundColor Green
    } else {
        $status.Issues += "Missing critical file: $file"
        Write-Host "  [MISSING] $($criticalFiles[$file])" -ForegroundColor Red
    }
}

# 3. Check AnyonicHO TUI Prerequisites
if (Get-Command cargo -ErrorAction SilentlyContinue) {
    $status.Components["Rust"] = "Installed"
    Write-Host "  [OK] Rust/Cargo detected" -ForegroundColor Green
} else {
    $status.Components["Rust"] = "Missing"
    $status.Issues += "Rust/Cargo not installed (required for TUI)"
    Write-Host "  [FAIL] Rust/Cargo not detected" -ForegroundColor Red
}

# 4. Extract WAVE Score (if available)
$waveFile = "$env:USERPROFILE\AnyonicHO\WAVE_GITHUB_ANALYSIS.md"
if (Test-Path $waveFile) {
    $content = Get-Content $waveFile -Raw
    if ($content -match "AVERAGE COHERENCE: (\d+\.\d+%)") {
        $score = $matches[1]
        $status["WaveScore"] = $score
        Write-Host "  [INFO] Current WAVE Coherence: $score" -ForegroundColor Cyan
    }
}

# 5. Output to JSON
$jsonPath = "$env:USERPROFILE\AnyonicHO\NETWORK_STATUS.json"
$status | ConvertTo-Json -Depth 4 | Set-Content $jsonPath
Write-Host "`nNetwork Status updated at $jsonPath" -ForegroundColor Gray
